---
# Branch maimul
title: "Parents’ Educational Background and Children’s Success"
author: "Maimul"
date: '2022-05-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("codebook")
library('ggplot2')
library('psych')
```


### Load file to r as dataframe
```{r}
df1 <- read.csv('~/Documents/Principle of DS/Project/datasets/student-mat.csv') # Change this according to the file name and directory of the file.

```



### Explore the dataset
```{r}
dim(df1) # Check the dimension of the dataset

# glimpse is better than str(). More organised, easy to read. 
# Also dim f(x) is baked into the glimpse.
glimpse(df1) # from tidyverse

# Explore the column names
names(df1)

# Before checking for missing values, list all unique values in the dataframe. Look for "" cells
unique(unlist(df1))
```
There are no empty cells to impute. Example: "" to NA

```{r}
# Check for missing data in df1
print(colSums(is.na(df1)))
```
No NA values. 

```{r}
# Before we change the datatypes we must check the unique values in each column.
lapply(df1, unique) # lapply always returns a list. 
```


### Change the datatype of each column accordingly 
```{r}
# List columns that should be factor (not ordered)
col_factors <- c('school', 'sex', 'address','Pstatus','Mjob','Fjob','reason','guardian')
df1[col_factors] <- lapply(df1[col_factors], factor)

# List columns that should be factor (ordered)
col_factorsO <- c('famsize')
df1[col_factorsO] <- lapply(df1[col_factorsO], ordered, levels = c('LE3','GT3'))

col_factorsO <- c(names(df1[24:29]),'Medu','Fedu','traveltime','studytime','famsize')
df1[col_factorsO] <- lapply(df1[col_factorsO], ordered)

# List columns that should be binary
col_binary <- c('schoolsup','famsup','paid','activities','nursery','higher','internet','romantic')
df1[col_binary]  <- ifelse(df1[col_binary] == 'yes',1,0)
df1[col_binary]  <- lapply(df1[col_binary], as.logical)


```

```{r}
# 4. Check for missing data
sum(is.na(df1))


# 9 List rows with missing data
df1[!complete.cases(df1), ]

# 11. Identify duplicate row
sum(duplicated(df1))  

# 12. Observe invalid values
describe(df1)
```



# Descriptive Analysis
```{r}
summary(df1)
sum(is.na(df1))

# Display all the unordered factors in bar-plot
for (i in col_factors){
  barplot(table(df1[i]), main = i, col = c('grey50',10,13,14,19,23))
}

# Display all the ordered factors in bar-plot
for (i in col_factorsO){
  barplot(table(df1[i]), main = i,col = c(7,10,13,14,19,23))
}

# Display all the logical values in bar-plot
for (i in col_binary){
  barplot(table(df1[i]), main = i,col = c(7,10,13,14,19,23))
}

# Boxplot for all integer columns
for (i in c('absences','G1','G2','G3')){
  boxplot(df1[i], main = i,col = c(7,10,13,14,19,23))
}
```

```{r}
# Remove outliers from absences column
outliers_up <- 8 + 1.5 * IQR(df1$absences) # only upper outliers as 1st quartile is 0 and makes sense to have 0 absence


nrow(df1)
paste0("There are ",sum(df1$absences > outliers_up)," outliers out of ",nrow(df1),".")
paste0(round((15/395)*100,2),"% of the values in the absences column are outliers and since it is less than 10% of the dataset we can remove the outliers.")

# Group by both fathers and mothers education
df1 %>% 
  select(Medu,Fedu,G3) %>% 
  group_by(Medu,Fedu) %>% 
  summarise(sum(G3))

# Group by mothers education
df1_Medu <- df1 %>% 
    select(Medu,G3) %>% 
    group_by(Medu) %>% 
    summarise(G3_sum = sum(G3))

# Scatter plot for mothers education vs grades
df1_Medu %>% 
  plot(G3_sum ~ Medu, main="Mother's education vs grades", 
   xlab="Mother's education level ", ylab="Grades of students")

# Group by fathers education
df1_Fedu <- df1 %>% 
    select(Fedu,G3) %>% 
    group_by(Fedu) %>% 
    summarise(G3_sum = sum(G3))

# Scatter plot for fathers education vs grades
df1_Fedu %>% 
  plot(G3_sum ~ Medu, main="Father's education vs grades", 
   xlab="Father's education level ", ylab="Grades of students")

# Group by mothers education and summarise failure
df1_Medu <- df1 %>% 
    select(Medu,failures) %>% 
    group_by(Medu) %>% 
    summarise(G3_sum = sum(failures))

# Scatter plot for mothers education vs failures
df1_Medu %>% 
  plot(G3_sum ~ Medu, main="Mother's education vs failures", 
   xlab="Mother's education level ", ylab="Failure of students")



# Group by fathers education and summarise failure
df1_Fedu <- df1 %>% 
    select(Fedu,failures) %>% 
    group_by(Fedu) %>% 
    summarise(G3_sum = sum(failures))

# Scatter plot for fathers education vs failures
df1_Fedu %>% 
  plot(G3_sum ~ Medu, main="Father's education vs failures", 
   xlab="Father's education level ", ylab="Failure of students")

# Ann
library(ggplot2)

# Histogram of age
hist(df1$age, main = "Distribution of student's age", xlab = "Student's age", ylab = "Number of student", col = "light blue")
# Histogram of absences
hist(df1$absences, main = "Distribution of student's absences", xlab = "Students absences", ylab = "Number of student", col = "light green")
# Histogram of average grade
average = (df1$G1 + df1$G2 + df1$G3)/3
average
hist(average, main = "Distribution of student's average grade", xlab = "Student's average grade", ylab = "Number of student", col = "yellow")
# bar graph of studytime & higher vs Medu
ggplot(df1, aes(x = Medu, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Mother's education level") +
  xlab("Mother's eduction level") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs Fedu
ggplot(df1, aes(x = Fedu, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Father's education level") +
  xlab("Father's eduction level") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs Mjob
ggplot(df1, aes(x = Mjob, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Mother's job") +
  xlab("Mother's job") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs Fjob
ggplot(df1, aes(x = Fjob, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Father's job") +
  xlab("Father's job") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs paid
ggplot(df1, aes(x = paid, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Extra paid classes") +
  xlab("Extra paid classes") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs famrel
ggplot(df1, aes(x = famrel, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Quality of family relationships") +
  xlab("Quality of family relationships") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))
# bar graph of studytime & higher vs health
ggplot(df1, aes(x = health, y = studytime, fill = higher)) + 
  geom_bar(position = "dodge", stat = "identity") +  
  ggtitle("Student's study time & Pursuing Higher education VS Current health status") +
  xlab("Current health status") + 
  ylab("Student's study time") +  
  scale_fill_manual("Pursuing higher education", values = c("light blue", "light green"))

```

```{r}
# Aainaa
barplot(table(df1$sex), main = "Distribution of Student's Gender", xlab = "Student's Gender", ylab = "Number of Student", names.arg = c("Female", "Male"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$age), main = "Distribution of Student's Age", xlab = "Student's Age", ylab = "Number of Student", col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$Pstatus), main = "Distribution of Parent's Cohabitation Status", xlab = "Parent's Cohabitation Status", ylab = "Number of Student", names.arg = c("Living Apart", "Living Together"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$Medu), main = "Distribution of Mother's Education", xlab = "Mother's Education", ylab = "Number of Student", names.arg = c("None", "4th Grade", "5-9th Grade", "Secondary Edu", "Higher Edu"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$Fedu), main = "Distribution of Father's Education", xlab = "Father's Education", ylab = "Number of Student", names.arg = c("None", "4th Grade", "5-9th Grade", "Secondary Edu", "Higher Edu"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(sort(table(df1$Mjob), decreasing = FALSE), main = "Distribution of Mother's Occupation", xlab = "Mother's Occupation", ylab = "Number of Student", names.arg = c("Healthcare", "Teacher", "Housewife", "Civil Services", "Other"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(sort(table(df1$Fjob), decreasing = FALSE), main = "Distribution of Father's Occupation", xlab = "Father's Occupation", ylab = "Number of Student", names.arg = c("Healthcare", "Househusband", "Teacher", "Civil Services", "Other"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$studytime), main = "Distribution of Weekly Study Time", xlab = "Study Time", ylab = "Number of Student", names.arg = c("< 2 hours", "2 to 5 hours", "5 to 10 hours", "> 10 hours"), col = c(7,10,13,14,19,23))
```

```{r}
# x axis labels are not clear
barplot(table(df1$failures), main = "Distribution of Pass Class Failures", xlab = "Pass Class Failures", ylab = "Number of Student", col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$paid), main = "Distribution of Extra Paid Class (Math)", xlab = "Extra Paid Class", ylab = "Number of Student", names.arg = c("No", "Yes"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$higher), main = "Distribution of Furthering Studies", xlab = "Higher Education", ylab = "Number of Student", names.arg = c("No", "Yes"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$internet), main = "Distribution of Home Internet Access", xlab = "Internet Access at Home", ylab = "Number of Student", names.arg = c("No", "Yes"),col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$romantic), main = "Distribution of Romantic Relationship", xlab = "In Romantic Relationship", ylab = "Number of Student", names.arg = c("No", "Yes"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$famrel), main = "Distribution of Student's Family Relationship", xlab = "Family Relationship", ylab = "Number of Student", names.arg = c("Very Bad", "Bad", "Average", "Good", "Excellent"), col = c(7,10,13,14,19,23))
```

```{r}
barplot(table(df1$health), main = "Distribution of Student's Health Status", xlab = "Current Health Status", ylab = "Number of Student", names.arg = c("Very Bad", "Bad", "Average", "Good", "Very Good"), col = c(7,10,13,14,19,23))
```

```{r}
boxplot(df1$absences, main = "Distribution of School Absences", xlab = "Students", ylab = "Number of School Absences", col = c(7,10,13,14,19,23))
```

```{r}
boxplot(df1$G1, main = "Distribution of First Period Grade", xlab = "Math", ylab = "First Period Grade", col = c(7,10,13,14,19,23))
```

```{r}
boxplot(df1$G2, main = "Distribution of Second Period Grade", xlab = "Math", ylab = "Second Period Grade", col = c(7,10,13,14,19,23))
```

```{r}
boxplot(df1$G3, main = "Distribution of Final Period Grade", xlab = "Math", ylab = "Final Period Grade", col = c(7,10,13,14,19,23))
```








```{r}
library('plyr')


df<-read.csv("~/Documents/Principle of DS/Project/WQD7001/ShinyApp7001/student-mat.csv")

# add a new column with the mean of G1 G2 and G3
df$score_mean <- rowMeans(subset(df, select = c(G1, G2, G2)), na.rm = TRUE)
# df = subset(df, select = -c(mean)) #drop mean column
describe(df$score_mean)
df
```

```{r}
# scatterplot of Medu vs Fedu
ggplot(df, aes(x=Medu, y=Fedu)) + geom_point()
# ggplot(df, aes(x=Fedu)) + geom_boxplot()
# ggplot(df, aes(x=Medu)) + geom_boxplot()
ggplot(df, aes(x = Medu, y = Fedu, fill = score_mean)) + geom_tile() + geom_text(aes(label = round(score_mean, digits = 0)), color = "white", size = 5)
```

```{r}
# avg score based on number of distinct in Medu/student 
Medu_score = c()
for (x in 0:4)
{
  Medu_score_mean = df[df$Medu==x, c("Medu" , "score_mean")]
  Medu_score = append(Medu_score,mean(Medu_score_mean$score_mean))
  cat(x, mean(Medu_score_mean$score_mean),"\n")
}
barplot(Medu_score,names.arg=c("0","1","2","3","4"),main = "avg test scores vs Medu",
xlab = "Medu",
ylab = "avg test scores", col = c(7,10,13,14,19,23))
```

```{r}
# avg score based on number of distinct in Fedu/student 
Fedu_score = c()
for (x in 0:4)
{
  Fedu_score_mean = df[df$Fedu==x, c("Fedu" , "score_mean")]
  Fedu_score = append(Fedu_score, mean(Fedu_score_mean$score_mean))
  cat(x, mean(Fedu_score_mean$score_mean),"\n")
}
barplot(Fedu_score,names.arg=c("0","1","2","3","4"),main = "avg test scores vs Fedu",
xlab = "Fedu",
ylab = "avg test scores", col = c(7,10,13,14,19,23))
```

```{r}
# scatterplot of failures vs Medu/Fedu
ggplot(df, aes(x=Medu, y=failures),col = c(7,10,13,14,19,23)) + geom_point()
ggplot(df, aes(x=Fedu, y=failures),col = c(7,10,13,14,19,23)) + geom_point()
```

```{r}
#avg of number of failures vs Medu
count(df$failures)
Medu_failure = c()
for (x in 0:4)
{
  Medu_failure_mean = df[df$Medu==x, c("Medu" , "failures")]
  Medu_failure = append(Medu_failure, mean(Medu_failure_mean$failures))
  cat(x, mean(Medu_failure_mean$failures),"\n")
}
barplot(Medu_failure,names.arg=c("0","1","2","3","4"),main = "avg number of failures vs Medu",
xlab = "Medu",
ylab = "avg number of failures",col = c(7,10,13,14,19,23))
```

```{r}
#avg of number of failures vs Fedu
Fedu_failure = c()
for (x in 0:4)
{
  Fedu_failure_mean = df[df$Fedu==x, c("Fedu" , "failures")]
  Fedu_failure = append(Fedu_failure, mean(Fedu_failure_mean$failures))
  cat(x, mean(Fedu_failure_mean$failures),"\n")
}
barplot(Fedu_failure,names.arg=c("0","1","2","3","4"),main = "avg number of failures vs Fedu",
xlab = "Fedu",
ylab = "avg number of failures",col = c(7,10,13,14,19,23))
```

```{r}
#total study time vs Medu
Medu_studytime = c()
for (x in 0:4)
{
  Medu_studytime_sum = df[df$Medu==x, c("Medu" , "studytime")]
  Medu_studytime = append(Medu_studytime, sum(Medu_studytime_sum$studytime))
  cat(x, sum(Medu_studytime_sum$studytime),"\n")
}
barplot(Medu_studytime,names.arg=c("0","1","2","3","4"),main = "study time vs Medu",
xlab = "Medu",
ylab = "total study time",col = c(7,10,13,14,19,23))
```


```{r}
#total study time vs Fedu
Fedu_studytime = c()
for (x in 0:4)
{
  Fedu_studytime_sum = df[df$Fedu==x, c("Fedu" , "studytime")]
  Fedu_studytime = append(Fedu_studytime, sum(Fedu_studytime_sum$studytime))
  cat(x, sum(Fedu_studytime_sum$studytime),"\n")
}
barplot(Fedu_studytime,names.arg=c("0","1","2","3","4"),main = "study time vs Fedu",
xlab = "Fedu",
ylab = "total study time",col = c(7,10,13,14,19,23))
```

```{r}
#total higher vs Medu
Medu_higher = c()
for (x in 0:4)
{
  Medu_higher_count = df[df$Medu==x, c("Medu" , "higher")]
  count_higher = count(Medu_higher_count$higher == 'yes')
  count_higher = data.frame(count_higher)
  Medu_higher = append(Medu_higher, count_higher[count_higher$x=='TRUE', c("freq")])
  cat(x, count_higher[count_higher$x=='TRUE', c("freq")],"\n")
}
barplot(Medu_higher,names.arg=c("0","1","2","3","4"),main = "total higher vs Medu",
xlab = "Medu",
ylab = "total higher",col = c(7,10,13,14,19,23))
```


```{r}
#total higher vs Fedu
Fedu_higher = c()
for (x in 0:4)
{
  Fedu_higher_count = df[df$Fedu==x, c("Fedu" , "higher")]
  count_higher = count(Fedu_higher_count$higher == 'yes')
  count_higher = data.frame(count_higher)
  Fedu_higher = append(Fedu_higher, count_higher[count_higher$x=='TRUE', c("freq")])
  cat(x, count_higher[count_higher$x=='TRUE', c("freq")],"\n")
}
barplot(Fedu_higher,names.arg=c("0","1","2","3","4"),main = "total higher vs Fedu",
xlab = "Fedu",
ylab = "total higher",col = c(7,10,13,14,19,23))
```

```{r}
count(df$Mjob)
count(df$Fjob)
```

```{r}
#avg of number of failures vs Medu
Medu_studytime = c()
for (x in 0:4)
{
  Medu_studytime_mean = df[df$Medu==x, c("Medu" , "studytime")]
  Medu_studytime = append(Medu_studytime, mean(Medu_studytime_mean$studytime))
  cat(x, mean(Medu_studytime_mean$studytime),"\n")
}
barplot(Medu_studytime,names.arg=c("0","1","2","3","4"),main = "avg number of failures vs Medu",
xlab = "Medu",
ylab = "avg number of failures",col = c(7,10,13,14,19,23))
```
