mainPanel(
  "Overview",br(),
  "It shows the 4 main research questions and infographic of answers to the questions.",br(),
  "",br(),
  "Descriptive Statistics",br(),
  "It shows the research project's dataset and statistics summary of the dataset. ",br(),
  "",br(),
  "Descriptive Analysis ",br(),
  "It shows the descriptive boxplot and barplot of the dataset",br(),
  "Boxplot",br(),
  "Input-Output: ",br(),
 " 1.	"absences" - Distribution of school absences",br(),
 " 2.	"G1" - Distribution of first period grade",br(),
 " 3.	"G3" - Distribution of second period grade",br(),
 " 4.	"G4" - Distribution of final period grade ",br(),
  "Barplot",br(),
  "Input-Output:",br(),
  "1.	"sex" - Distribution of student's gender",br(),
  "2.	"age" - Distribution of student's age",br(),
  "3.	"Pstatus" - Distribution of parent's cohabitation status",br(),
  "4.	"Medu" - Distribution of mother's education",br(),
  "5.	"Fedu" - Distribution of father's education",br(),
  "6.	"Mjob" - Distribution of mother's occupation",br(),
  "7.	"Fjob" - Distribution of father's occupation",br(),
  "8.	"studytime" - Distribution of weekly study time",br(),
  "9.	"failures" - Distribution of pass class failures",br(),
  "10.	"paid" - Distribution of extra paid class (math)",br(),
  "11.	"higher" - Distribution of furthering studies",br(),
  "12.	"internet" - Distribution of home internet access",br(),
  "13.	"romantic" - Distribution of romantic relationship",br(),
  "14.	"famrel" - Distribution of student's home relationship",br(),
  "15.	"health" - Distribution of student's health status",br(),
  "",br(),
  "Exploratory Descriptive Analysis",br(),
  "It shows the exploratory descriptive analysis of the relationship between Father's and mother's education with students' average test score, number of test failures, study time and intention to go for higher education. It has 2 different barplot tab for input where each of it consists of the following input option: ",br(),
  "Barplot input tab 1: Father's education and mother's education",br(),
  "Barplot input tab 2: Average test scores, Failures, Study time and Higher",br(),
  "The output will be a barplot displaying at the right side of the page where it shows the relationship between the first and second selected variables." ,br(),
  "There is also an option for highlighting the intended barplot column. Just by clicking the square box at the left hand side of "Highlight by education level", an scale bar will appear for you to select your intended barplot column to highlight.",br(),
),